### ISSUE TITLE
[The Merge] - Understand all the changes to the `eth1` data structure

### ISSUE THREAD

**Issue by abdulrabbani00** [vulcanize/go-ethereum#219] opened 2022-03-31 17:45 UTC
All changes to the `eth1` data structure post-merge must be captured and understood. These changes need to be handled in multiple places, so they should be documented and clearly understood.

**Comment by i-norden** [comment] 2022-04-06 12:42
This looks like duplicate of #220, re-open if I am mistaken (but the comment is the same).

**Closed as completed by i-norden** 2022-04-06 12:42 UTC

**Comment by abdulrabbani00** [comment] 2022-04-06 12:44
@i-norden - They're similar, this ticket's purpose is to highlight that we need to understand the changes while the other ticket is for actually implementing the changes. Since @ashwinphatak and his team will be working on this task, I will leave it up to them to decide if they need this ticket or if it's too redundant.
