### ISSUE TITLE
State diffing at head can leave gaps

### ISSUE THREAD

**Issue by dboreham** [vulcanize/go-ethereum#393] opened 2023-06-01 13:44 UTC
If some fatal error occurs in state diffing inside geth (such as [this](https://github.com/cerc-io/go-ethereum/issues/367)), after re-start a gap in the set of state diff data in the database can result. 

geth shouldn't leave gaps even when it exits due to a fatal error / crash and is re-started.

**Comment by i-norden** [comment] 2023-06-01 14:34
Related:

* https://github.com/cerc-io/issue_tracking/issues/11
* https://github.com/vulcanize/ops/issues/201
* https://github.com/cerc-io/go-ethereum/issues/131
* https://github.com/cerc-io/go-ethereum/issues/292
* See https://github.com/cerc-io/go-ethereum/issues?q=is%3Aissue+known+is%3Aclosed
* https://github.com/cerc-io/go-ethereum/pull/217
* https://github.com/cerc-io/go-ethereum/pull/223

**Comment by telackey** [comment] 2023-06-12 20:05
Gap detection and filling has been added to https://git.vdb.to/cerc-io/chain-chunker .

It is useful when there are known to be gaps (eg, after an incident) and could be used to fill smaller gaps, such as those created by restarting the containers automatically (eg, by cron job).

In short, in makes it quite easy to fix gaps, however, it does nothing to _prevent_ gaps, which is more of the the issue here.

Statediffing for head is triggered by the event feed for the blockchain.  These events are triggered _after_ the block is processed by geth.  When geth is restarted, it will start syncing from the last block it successfully processed.  However, statediffing (since it is event based) will start from the _next_ block that geth processes.  This allows for small gaps to open, since any statediffs which were in-flight at the time geth was restarted will not be triggered again.

The likely fix is to add a check (probably on restart, but perhaps periodic) which looks for any gap between the current block_number and `max(block_number) from eth.header_cids` and triggers statediffing accordingly.

**Comment by telackey** [comment] 2023-06-12 20:06
I'm going to close this one as a duplicate of https://github.com/cerc-io/go-ethereum/issues/292

**Closed as not planned by telackey** 2023-06-12 20:06 UTC
